version: "3"
services:
  ollama:
    image: ollama/ollama:0.1.34
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama_net

  flashcard_generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./study_guides:/app/study_guides
      - ./flashcards:/app/flashcards
      - ./output:/app/output
    depends_on:
      - ollama
    networks:
      - ollama_net

volumes:
  ollama_data:

networks:
  ollama_net:
    driver: bridge
