import os
import time
import requests  # pyright: ignore
import pandas as pd  # pyright: ignore
from typing import List, Dict


class FlashcardGenerator:
    def __init__(self, ollama_url: str = "http://ollama:11434/api/generate"):
        """
        Initialize the Flashcard Generator with Ollama API endpoint

        :param ollama_url: URL of the Ollama API for generating flashcards
        """
        self.ollama_url = ollama_url
        self.model = "tinyllama"  # Default model, can be changed

    def test_ollama_connection(self) -> bool:
        """
        Test connection to Ollama and generate a sample flashcard

        :return: Boolean indicating successful connection and flashcard generation
        """
        try:
            # Test connection
            test_response = requests.get(
                f"{self.ollama_url.replace('/generate', '')}/version"
            )
            # print(test_response.text)
            test_response.raise_for_status()

            print("Ollama Connection Test:")
            print("✅ API Version Check: Success")

            return True

        except requests.exceptions.RequestException as e:
            print(f"❌ Ollama Connection Failed: {e}")
            return False

    def pull_model(self):
        """
        Pull a model from the Ollama API
        """
        try:
            print(f"Pulling model: {self.model}")
            response = requests.post(
                f"{self.ollama_url.replace('/generate', '')}/pull",
                json={"model": self.model, "stream": False},
            )
            # print(response.json())
            response.raise_for_status()
            print(f"Model {self.model} pulled successfully")
        except Exception as e:
            print(f"Error pulling model: {e}")

    def check_model(self) -> bool:
        """
        check if the model is already pulled from the Ollama API
        """
        try:
            print(f"Checking model: {self.model}")
            response = requests.get(
                f"{self.ollama_url.replace('/generate', '')}/tags",
            )
            # print(response.json())
            response.raise_for_status()
            for model in response.json().get("models", []):
                if self.model in model["name"]:
                    print(f"Model {self.model} already pulled")
                    return True
            print(f"Model {self.model} not pulled")
            return False
        except Exception as e:
            print(f"Error checking model: {e}")
            return False

    def parse_study_guide(self, file_path: str) -> str:
        """
        Parse study guide from different file types

        :param file_path: Path to the study guide file
        :return: The whole content of the study guide
        """
        # Support only Markdown files
        file_extension = os.path.splitext(file_path)[1].lower()

        if file_extension == ".md":
            with open(file_path, "r") as file:
                contents = file.read()
            return contents

        else:
            return ""

    def generate_flashcards(self, content: str) -> str:
        """
        Generate a flashcard using Ollama API

        :param content: Content section to generate flashcard from
        :return: Dictionary with question and answer
        """
        prompt = f"""
        Create a list of detailed flashcards from the following study material:
        
        Material: 

        {content}
        
        Please provide:
        1. A clear, concise question that tests understanding
        2. A comprehensive answer that covers key points
        
        Format your response as:
        Question 1: [Your question 1 here]
        Answer 1: [Detailed answer 1 here]

        Question 2: [Your question 2 here]
        Answer 2: [Detailed answer 2 here]

        ... 

        Question n: [Your question n here]
        Answer n: [Detailed answer n here]
        """
        try:
            response = requests.post(
                self.ollama_url,
                json={"model": self.model, "prompt": prompt, "stream": False},
            )
            print(response.json())
            response.raise_for_status()

            generated_text = response.json()["response"]

            return generated_text

        except Exception as e:
            print(f"Error generating flashcard: {e}")
            return ""

    def parse_flashcards(self, flashcards: str) -> List[Dict[str, str]]:
        """
        Parse the generated flashcards into a list of dictionaries

        :param flashcards: Flashcards generated by the API
        :return: List of dictionaries with question and answer
        """
        flashcards_list = flashcards.split("\n\n")

        parsed_flashcards = []
        for i in range(0, len(flashcards), 2):
            question = flashcards_list[i].split(":")[1].strip()
            answer = flashcards_list[i + 1].split(":")[1].strip()

            parsed_flashcards.append({"Question": question, "Answer": answer})

        return parsed_flashcards

    def return_flashcards(self, file_path: str, output_file: str = "flashcards.xlsx"):
        """
        Generate flashcards from a study guide and save to Excel

        :param file_path: Path to the study guide
        :param output_file: Path to save the Excel file
        """
        # Parse study guide
        contents = self.parse_study_guide(file_path)

        if not contents:
            print("Study guide parsing failed. Please check the file type.")
            return

        # Generate flashcards
        flashcards = self.generate_flashcards(contents)

        if not flashcards:
            print("Flashcards generation failed. Please try again.")
            return

        parsed_flashcards = self.parse_flashcards(flashcards)

        # Create DataFrame and save to Excel
        df = pd.DataFrame(parsed_flashcards)
        df.to_excel(output_file, index=False)
        print(f"Flashcards generated and saved to {output_file}")


def main():
    # wait 30 seconds for ollama to start
    time.sleep(10)

    # Create generator instance
    generator = FlashcardGenerator()

    # Test Ollama connection first
    if not generator.test_ollama_connection():
        print("Cannot proceed. Ollama connection test failed.")

    # Check if the model is already pulled
    if not generator.check_model():
        generator.pull_model()

    # Generate flashcards from study guide
    generator.generate_flashcards("study_guide.txt")


if __name__ == "__main__":
    main()
